import Foundation
import TorrentEngineModel
@testable import TorrentApp

func makeTorrent(
    id: String = UUID().uuidString,
    infoHash: String = "hash",
    name: String = "Torrent",
    savePath: String = "/tmp/downloads",
    error: String = "",
    comment: String = "",
    progress: Double = 0,
    totalDone: Int64 = 0,
    totalWanted: Int64 = 100,
    totalSize: Int64 = 100,
    totalUpload: Int64 = 0,
    totalDownload: Int64 = 0,
    totalPayloadUpload: Int64 = 0,
    totalPayloadDownload: Int64 = 0,
    allTimeUpload: Int64 = 0,
    allTimeDownload: Int64 = 0,
    addedTime: Int64 = 0,
    createdTime: Int64 = 0,
    completedTime: Int64 = 0,
    downloadRate: Int32 = 0,
    uploadRate: Int32 = 0,
    downloadPayloadRate: Int32 = 0,
    uploadPayloadRate: Int32 = 0,
    peers: Int32 = 0,
    knownPeers: Int32 = 0,
    seeds: Int32 = 0,
    state: TorrentState = .unknown,
    queuePosition: Int32 = -1,
    queuePriority: TorrentQueuePriority = .normal,
    paused: Bool = false,
    autoManaged: Bool = false,
    seeding: Bool = false,
    finished: Bool = false,
    hasMetadata: Bool = true,
    privateTorrent: Bool = false
) -> TorrentItem {
    TorrentItem(
        id: id,
        infoHash: infoHash,
        name: name,
        savePath: savePath,
        error: error,
        comment: comment,
        progress: progress,
        totalDone: totalDone,
        totalWanted: totalWanted,
        totalSize: totalSize,
        totalUpload: totalUpload,
        totalDownload: totalDownload,
        totalPayloadUpload: totalPayloadUpload,
        totalPayloadDownload: totalPayloadDownload,
        allTimeUpload: allTimeUpload,
        allTimeDownload: allTimeDownload,
        addedTime: addedTime,
        createdTime: createdTime,
        completedTime: completedTime,
        downloadRate: downloadRate,
        uploadRate: uploadRate,
        downloadPayloadRate: downloadPayloadRate,
        uploadPayloadRate: uploadPayloadRate,
        peers: peers,
        knownPeers: knownPeers,
        seeds: seeds,
        state: state,
        queuePosition: queuePosition,
        queuePriority: queuePriority,
        paused: paused,
        autoManaged: autoManaged,
        seeding: seeding,
        finished: finished,
        hasMetadata: hasMetadata,
        privateTorrent: privateTorrent
    )
}
